name: CI/CD for Animal Identification app

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Build Docker image inside Minikube
        run: |
          eval $(minikube docker-env)
          docker build -t animal-identification-app:latest .

      - name: Load image into Minikube
        run: |
          minikube image load animal-identification-app:latest

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
