apiVersion: v1
kind: Service
metadata:
  name: animal-identification-app
spec:
  selector:
    app: animal-identification-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort