{
 "title": "Animal Identification Metrics Dashboard",
 "time": { "from": "2025-06-26T08:54:41.681Z", "to": "2025-06-26T12:22:10.017Z" },
 "panels": [
  {
   "title": "Total API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "total_api_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Confidence Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "latest_prediction_confidence", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "request_processing_latency_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}